/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExpandablePanel {
    }
    interface HighContrastToggle {
    }
    interface MandatoryInput {
    }
    interface MultiSelectionList {
        "options": string[];
    }
    interface NotesCard {
    }
}
declare global {
    interface HTMLExpandablePanelElement extends Components.ExpandablePanel, HTMLStencilElement {
    }
    var HTMLExpandablePanelElement: {
        prototype: HTMLExpandablePanelElement;
        new (): HTMLExpandablePanelElement;
    };
    interface HTMLHighContrastToggleElement extends Components.HighContrastToggle, HTMLStencilElement {
    }
    var HTMLHighContrastToggleElement: {
        prototype: HTMLHighContrastToggleElement;
        new (): HTMLHighContrastToggleElement;
    };
    interface HTMLMandatoryInputElement extends Components.MandatoryInput, HTMLStencilElement {
    }
    var HTMLMandatoryInputElement: {
        prototype: HTMLMandatoryInputElement;
        new (): HTMLMandatoryInputElement;
    };
    interface HTMLMultiSelectionListElement extends Components.MultiSelectionList, HTMLStencilElement {
    }
    var HTMLMultiSelectionListElement: {
        prototype: HTMLMultiSelectionListElement;
        new (): HTMLMultiSelectionListElement;
    };
    interface HTMLNotesCardElement extends Components.NotesCard, HTMLStencilElement {
    }
    var HTMLNotesCardElement: {
        prototype: HTMLNotesCardElement;
        new (): HTMLNotesCardElement;
    };
    interface HTMLElementTagNameMap {
        "expandable-panel": HTMLExpandablePanelElement;
        "high-contrast-toggle": HTMLHighContrastToggleElement;
        "mandatory-input": HTMLMandatoryInputElement;
        "multi-selection-list": HTMLMultiSelectionListElement;
        "notes-card": HTMLNotesCardElement;
    }
}
declare namespace LocalJSX {
    interface ExpandablePanel {
    }
    interface HighContrastToggle {
    }
    interface MandatoryInput {
    }
    interface MultiSelectionList {
        "options"?: string[];
    }
    interface NotesCard {
    }
    interface IntrinsicElements {
        "expandable-panel": ExpandablePanel;
        "high-contrast-toggle": HighContrastToggle;
        "mandatory-input": MandatoryInput;
        "multi-selection-list": MultiSelectionList;
        "notes-card": NotesCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "expandable-panel": LocalJSX.ExpandablePanel & JSXBase.HTMLAttributes<HTMLExpandablePanelElement>;
            "high-contrast-toggle": LocalJSX.HighContrastToggle & JSXBase.HTMLAttributes<HTMLHighContrastToggleElement>;
            "mandatory-input": LocalJSX.MandatoryInput & JSXBase.HTMLAttributes<HTMLMandatoryInputElement>;
            "multi-selection-list": LocalJSX.MultiSelectionList & JSXBase.HTMLAttributes<HTMLMultiSelectionListElement>;
            "notes-card": LocalJSX.NotesCard & JSXBase.HTMLAttributes<HTMLNotesCardElement>;
        }
    }
}
